## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : Python 분석라이브러리 활용

- 평가일 : 21.7. 23
- 성명 : 
- 점수 : 40  
맞힌 문제 : 1,2,4,5,6,8,9,14  
틀린 문제 : 3,7,10,11,12,13,15,16,17,18,19,20

### Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
[0 1 2 3 4 5 6 7 8 9]  

[[0 1 2 3 4]  
 [5 6 7 8 9]]  
 
[[[0 1 2 3 4]  
  [5 6 7 8 9]]]

In [32]:
import numpy as np
import pandas as pd

ar1 = np.arange(10) # 1차원
print(ar1)
print()

ar2 = np.arange(10).reshape(2,5) # 2차원
print(ar2)
print()

ar3 = np.arange(10).reshape(1,2,5) # 3차원
# ar3 = ar.reshape(-1,2,5)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


### Q2. 1 ~ 100 까지 배열에서 3과 7의 공배수인 것만을 출력하세요.

In [33]:
arr = np.arange(1,101) # 앞에 1을 붙여줘야 한다. 디폴트는 0부터 시작이기 때문.
for i in arr:
    if i%3==0 and i%7==0:
        print(i.reshape(-1))
    else:
        continue

[21]
[42]
[63]
[84]


In [35]:
# A.
import numpy as np
a1 = np.arange(1, 101)
a1 = a1[(a1 % 3 ==0) & (a1 % 7==0)]
# a1 = a1[(a1%3 == 0) and (a1%7==0)]  -> 이건 & 대신 and 가 들어가서 안 된다.
a1

array([21, 42, 63, 84])

### Q3. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3  4]  
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]  
   [15 16 17 18 19]]

 [[20 21 22 23 24]  
   [25 26 27 28 29]]]

In [41]:
# A.
arr3d = np.arange(30).reshape(3,2,5)
print(arr3d)

arr1d = arr3d.reshape(-1,) # 그냥 -1 해도 되지만 오류 방지를 위한 , 를 뒤에 붙이는 것이 좋다.
arr1d

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
ar = np.arange(10).reshape(1,2,5)
print(ar)
print(ar.reshape(2,5))
print()

ar2 = np.arange(10,20).reshape(1,2,5)
print(ar2)
print(ar2.reshape(2,5))
print()

ar3 = np.arange(20,30).reshape(1,2,5)
print(ar3)
print(ar3.reshape(2,5))

[[[0 1 2 3 4]
  [5 6 7 8 9]]]
[[0 1 2 3 4]
 [5 6 7 8 9]]

[[[10 11 12 13 14]
  [15 16 17 18 19]]]
[[10 11 12 13 14]
 [15 16 17 18 19]]

[[[20 21 22 23 24]
  [25 26 27 28 29]]]
[[20 21 22 23 24]
 [25 26 27 28 29]]


### Q4. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(1,10).reshape(3,3)

[3, 6]  

[[1, 2],  
[4, 5]]

[[1, 2, 3]  
[4, 5, 6]]

In [63]:
# A.
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)
print()
# print(arr2d[0,1]) # 인자만 뽑아내네.
# print(arr2d[[0,2]]) # 1행, 3행을 뽑아낸다.
print(arr2d[[0,1],2]) # 1행, 2행 중에서 3번열을 뽑아낸다.
# print(arr2d[[0,1],[0,1]]) # 1행의 1열, 2행의 2열을 뽑아낸다.
print(arr2d[[0,1],0:2]) # 열은 범위를 줬기에 [] 를 씌우면 syntax error가 난다.
print(arr2d[[0,1],:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


### Q5. 아래 두행렬을 np.arange, reshape를 이용해서 생성 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하세요.

[[1 2 3]  
 [4 5 6]  
 [7 8 9]]

[[10 11 12]  
 [13 14 15]  
 [16 17 18]]

In [64]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
ab_product = np.dot(a,b) # np.dot 내적 식 -> 행 곱
print(a,'\n')
print(b,'\n')
print(ab_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[10 11 12]
 [13 14 15]
 [16 17 18]] 

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [26]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
print()
b1 = np.arange(10,19).reshape(3,3)
print(b1)
print()
a1b1_product = np.dot(a1,b1)
print(a1b1_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


### Q6. ar의 역행렬을 출력하고 검증을 수행하세요.

In [65]:
np.random.seed(0)
ar = np.random.randint(1,4,size=(3,3))# (인자 범위,로 주고 , size=() )
ar

array([[1, 2, 1],
       [2, 2, 3],
       [1, 3, 1]])

In [66]:
b = np.linalg.inv(ar) # 역행렬 np.linalg.inv(ar)
b

array([[ 7., -1., -4.],
       [-1.,  0.,  1.],
       [-4.,  1.,  2.]])

In [67]:
np.dot(ar,b) # 위의 두 행렬을 내적 => 서로 역행렬의 관계라는 것 검증

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Q7. 10 ~ 20 사이의 정수 난수로 10행 5열 2차원 배열을 생성하고 저장한 후 다시 불러내서 출력하세요.

In [69]:
# A.
import numpy as np
import pandas as pd
np.random.seed(0)
ar = np.random.randint(10,20,size=(10,5))
np.save('ar_test',ar) # np.save('저장할 이름', 해당 변수명)
np.load('ar_test.npy') # np.load('불러올 파일명 확장자까지')

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11],
       [19, 19, 10, 14, 17],
       [13, 12, 17, 12, 10]])

In [9]:
# 2차원 만들라고 했는데 3차원 만들었다.
a7 = np.random.randint(10,20,size=(10,5,2))
a7

array([[[18, 11],
        [16, 17],
        [17, 18],
        [11, 15],
        [19, 18]],

       [[19, 14],
        [13, 10],
        [13, 15],
        [10, 12],
        [13, 18]],

       [[11, 13],
        [13, 13],
        [17, 10],
        [11, 19],
        [19, 10]],

       [[14, 17],
        [13, 12],
        [17, 12],
        [10, 10],
        [14, 15]],

       [[15, 16],
        [18, 14],
        [11, 14],
        [19, 18],
        [11, 11]],

       [[17, 19],
        [19, 13],
        [16, 17],
        [12, 10],
        [13, 15]],

       [[19, 14],
        [14, 16],
        [14, 14],
        [13, 14],
        [14, 18]],

       [[14, 13],
        [17, 15],
        [15, 10],
        [11, 15],
        [19, 13]],

       [[10, 15],
        [10, 11],
        [12, 14],
        [12, 10],
        [13, 12]],

       [[10, 17],
        [15, 19],
        [10, 12],
        [17, 12],
        [19, 12]]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived'외에 모든 칼럼을 포함한 df_x를 산출한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [108]:
df = sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [110]:
# A.
import seaborn as sns
import pandas as pd

# titanic 데이터셋 가져오기
df = sns.load_dataset('titanic')
df_x = df.drop('survived',axis=1) #@ axis=1 은 행 기준. 왜 행 기준을 drop 하지?
df_x.to_pickle('C:/workspace/cakd3/pandas/dataset/df_x.pkl') # to_pickle -> pkl 파일로 저장
df_x = pd.read_pickle('C:/workspace/cakd3/pandas/dataset/df_x.pkl') # pkl파일 읽기 -> pd.read_pickle ->df_x 란 이름으로 df_x.pkl 파일을 불러온다.
# df_x.to_pickle('dataset/df_x.pkl')  # 이 경로는 왜 안 될까. 강의실 내에서는 아무도 알지 못 한다.
# df_x = pd.read_pickle('dataset/df_x.pkl')
df_x.head()

pclass     sex   age  sibsp  parch     fare embarked  class    who  \
0       3    male  22.0      1      0   7.2500        S  Third    man   
1       1  female  38.0      1      0  71.2833        C  First  woman   
2       3  female  26.0      0      0   7.9250        S  Third  woman   
3       1  female  35.0      1      0  53.1000        S  First  woman   
4       3    male  35.0      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [71]:
import seaborn as sns
df= sns.load_dataset('titanic')
df

df_x = df.drop(['survived'],axis=1,)
df_x

df_x.to_pickle('C:/workspace/cakd3/pandas/dataset/df_x.pkl')
df_x = pd.read_pickle('C:/workspace/cakd3/pandas/dataset/df_x.pkl')
df_x.head()

pclass     sex   age  sibsp  parch     fare embarked  class    who  \
0       3    male  22.0      1      0   7.2500        S  Third    man   
1       1  female  38.0      1      0  71.2833        C  First  woman   
2       3  female  26.0      0      0   7.9250        S  Third  woman   
3       1  female  35.0      1      0  53.1000        S  First  woman   
4       3    male  35.0      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

### Q9. df = sns.load_dataset('titanic')로 불러와서 deck 열에서 NaN 갯수를 계산하세요.

In [104]:
# A.
# deck 열의 NaN 개수 계산하기

df = sns.load_dataset('titanic') # sns에 load_dataset('') 기능이 있구나
print(df['deck'].isnull().sum(axis=0)) # df에 ['열 이름']에서 .isnull()로 NaN 값을 가져온 후 .sum(axis=1)로 열에 속한 NaN값 행들을 전부 더한다.
# print(df['deck'].isnull()) 를 일단 출력 해보면, 왜 sum에 axis=0 를 적용했는지 알 수 있다.

# axis = 0 은 열 기준이니 수직으로 전부 처리. # 디폴트 값
# axis = 1 은 행 기준이니 수평으로 전부 처리.

688


### Q10. Q9의 df에서 각 칼럼별 null 개수와 df 전체의 null 개수를 구하세요.

In [111]:
print(df.isnull())

     survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False      

In [106]:
# A.
# 각 칼럼별 null 개수
# print(df.isnull())
print(df.isnull().sum()) # 열은 디폴트 값이라 sum(axis=0) 을 안 하고 sum() 만 해줘도 된다.
print()
print(df.isnull().sum().sum()) # 위에서 구한 df 의 형태가 1열의 형태이니, axis = 0을 이용해 sum을 구하면 모든 값을 처리할 수 있다.

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

869


### 아래 tdf 데이터프레임에서 Q11 ~ Q12 작업을 수행하세요.

In [112]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

### Q11. age를 7개 카테고리로 구분하는 새로운 칼럼 'cat_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 age 칼럼에 매핑하여 결과를 tdf1에 저장하고 출력하세요.

[카테고리]  
age <= 5: cat = 'Baby'  
age <= 12: cat = 'Child'  
age <= 18: cat = 'Teenager'  
age <= 25: cat = 'Student'  
age <= 60: cat = 'Adult'  
age > 60 : cat = 'Elderly'

In [126]:
# A.
def cat_age(x): #@ 사용자 함수를 만드네. 이걸 언제 만들어야 할지 잘 생각해보자.
    cat = ''
    if   x <= 5   :  cat = 'Baby'
    elif x <= 12  :  cat = 'Child'
    elif x <= 18  :  cat = 'Teenager'
    elif x <= 25  :  cat = 'Student'
    elif x <= 60  :  cat = 'Adult'
    else : cat = 'Elderly' #  x 없이 : 을 붙여야 한다. -> else: 형식이니까 그렇지 뭐. if: 듯이. 한 칸 아래로 내리기가 익숙하지 않아서 생각을 좀 해야 했다.
        
    return cat

tdf1 = tdf.copy()
tdf1['age_cat'] = tdf.age.apply(cat_age)

tdf1.head()

survived     sex   age  class  age_cat
0         0    male  22.0  Third  Student
1         1  female  38.0  First    Adult
2         1  female  26.0  Third    Adult
3         1  female  35.0  First    Adult
4         0    male  35.0  Third    Adult

In [ ]:
tdf1 = tdf.agg({'cat_age':['survived','sex','age','class']})
tdf1

### Q12.  tdf1의 sex, class 칼럼을 '_'으로 연결한 'sc'칼럼을 추가한 후 아래와 같이 출력하세요.



In [144]:
# tdf1['sc'] = tdf1[['sex','class']]
tdf1['sc'] = tdf1[['sex','class']].agg('_'.join, axis=1) # .agg('_'.join, axis=1) => 뒤에 _Third , _First 등의 순서를 붙인다.
# agg is the same as aggregate. It's callable is passed the columns (Series objects) of the DataFrame, one at a time.
## aggregate의 약자. 종합적인, 통합, 총계.. 한 번에 하나씩 불러옴. for과 비슷한 개념이네.
# https://stackoverflow.com/questions/15322632/python-pandas-df-groupby-agg-column-reference-in-agg

# agg 는 [] 적용할 수 없다.
# tdf1['sc'] 를 정의해줌으로써 칼럼 추가를 하네['열 이름']
#@ axis = 1 => 행을 기준으로 처리하네. 행 하나하나 전부 적용하려고 하는 듯.
tdf1.head()

survived     sex   age  class  age_cat            sc
0         0    male  22.0  Third  Student    male_Third
1         1  female  38.0  First    Adult  female_First
2         1  female  26.0  Third    Adult  female_Third
3         1  female  35.0  First    Adult  female_First
4         0    male  35.0  Third    Adult    male_Third

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- df1과 df2의 교집합만 출력되도록 결합하여 df4에 저장하고 출력
- df4에서 중복된 칼럼을 삭제한 후 블린 인덱싱을 이용하여 eps가 3000 보다 적거나 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df5 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [135]:
# A.

df1 = pd.read_excel('C:/workspace/cakd3/과제 + 시험/stock price.xlsx', index_col='id')
df2 = pd.read_excel('C:/workspace/cakd3/과제 + 시험/stock valuation.xlsx', index_col='id')
df4 = df1.join(df2, how='inner') # df1과 df2의 교집합만 출력되도록 결합하여 df4에
# how='inner' 는 join( 데이터프레임 명 , ) 의 디폴트 값이다.
# - inner join 을 A 와 B에 대해 수행하는 것은, A와 B의 교집합을 말합니다. 벤다이어그램으로 그렸을 때 교차되는 부분입니다.
# - outer join을 A와 B에 대해 수행하는 것은, A와 B의 합집합을 말합니다. 벤다이어 그램으로 그렸을 때, 합집합 부분입니다.
# 출처: https://stanleykou.tistory.com/entry/SQL-INNER-조인과-OUTER조인이-무엇인가요 [StanleyKou의 개인작업실]
print(df4)
print()
df4.drop('name', axis=1, inplace=True) # stock_name과 name은 서로 중복되는 값이므로 칼럼 삭제.
# inplace=True => 값을 계산한 후 사본을 삭제


df5 = df4[(df4['eps'] < 3000) | (df4['stock_name'] == '이마트')] # 이거나. 합집함을 선택 해야겠지.
df5

       stock_name          value   price    name           eps     bps  \
id                                                                       
130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068   
139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090   
185750        종근당   40293.666667  100500     종근당   3990.333333   40684   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

              per       pbr  
id                           
130960  15.695091  1.829178  
139480  13.931338  0.860437  
145990  14.283226  0.758627  
185750  25.185866  2.470259  
204210  40.802348  0.651359  



stock_name          value   price           eps     bps        per  \
id                                                                          
139480        이마트  239230.833333  254500  18268.166667  295780  13.931338   
204210     모두투어리츠    3093.333333    3475     85.166667    5335  40.802348   

             pbr  
id                
139480  0.860437  
204210  0.651359

inplace매개 변수 :

df.dropna(axis='index', how='all', inplace=True)
의 Pandas일반적인 수단 :

1. Pandas는 원본 데이터의 복사본을 만듭니다.

2. ... 그것에 대해 약간의 계산을 수행합니다.

3. ... 결과를 원본 데이터에 할당합니다.

4. ... 사본을 삭제합니다. -> inplace=True

https://stackoverflow.com/questions/43893457/understanding-inplace-true

### Q14. 아래 df에서 drop_duplicates() 메소드를 사용하여 c4, c5열을 기준으로 중복 행을 제거한 후 df3에 저장하고 출력하세요.

In [17]:
# 중복 데이터를 갖는 데이터프레임 만들기
import pandas as pd
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2],
                  'c4':[1, 1, 1, 2, 3],
                  'c5':[1, 1, 2, 2, 5]})
print(df)

  c1  c2  c3  c4  c5
0  a   1   1   1   1
1  a   1   1   1   1
2  b   1   2   1   2
3  a   2   2   2   2
4  b   2   2   3   5


In [18]:
# A.
# c4, c5 칼럼을 기준으로 중복 행을 제거
df3 = df.copy()

# df3.drop_duplicates()
df3.drop_duplicates(['c4','c5'])

c1  c2  c3  c4  c5
0  a   1   1   1   1
2  b   1   2   1   2
3  a   2   2   2   2
4  b   2   2   3   5

### Q15. 'mpg'를 'kpl' 로 환산하여 새로운 열을 생성하고 처음 3개 행을 소수점 아래 둘째 자리에서 반올림하여 출력하세요.

In [145]:
# read_csv() 함수로 df 생성
import pandas as pd
auto_df = pd.read_csv('C:/workspace/cakd3/pandas/auto-mpg.csv')

# 열 이름을 지정
auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
# auto_df.columns -> auto_df 변수의 칼럼 -> .columns
print(auto_df.head(3)) 

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  


In [146]:
# A.
# mpg(mile per gallon)를 kpl(kilometer per liter)로 변환 (mpg_to_kpl = 0.425)
mpg_to_kpl = 1.60934 / 3.78541

# mpg 열에 0.425를 곱한 결과를 새로운 열(kpl)에 추가
auto_df['kpl'] = auto_df['mpg'] * mpg_to_kpl # mpg_to_kpl이 0.425의 값을 가지니까 변수 째로 그대로 곱해주네.
print(auto_df.head(3))    
print('\n')

# kpl 열을 소수점 아래 둘째 자리에서 반올림 
auto_df['kpl'] = auto_df['kpl'].round(2)
print(auto_df.head(3))     

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   

   origin                       name       kpl  
0       1  chevrolet chevelle malibu  7.652571  
1       1          buick skylark 320  6.377143  
2       1         plymouth satellite  7.652571  


    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1        

### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 datetime64 자료형으로 변환한 후에 년, 월, 일로 분리하고 year를 인덱스로 셋팅하여 출력하세요.

In [184]:
# A.
# 날짜 데이터 분리

import pandas as pd

# read_csv() 함수로 파일 읽어와서 df로 변환
## -> DataFrame으로 불러온다고.
df = pd.read_csv('C:/workspace/cakd3/pandas/stock-data.csv')

# 문자열인 날짜 데이터를 판다스 Timestamp로 변환 
## -> datetime64 자료형으로 변환한다고.
df['new_Date'] = pd.to_datetime(df['Date'])   #df에 새로운 열로 추가
df.drop('Date',axis=1,inplace=True) # inplace=True -> 안 넣으면 에러 난다.

# dt 속성을 이용하여 new_Date 열의 년월일 정보를 년, 월, 일로 구분
df['Year'] = df['new_Date'].dt.year
df['Month'] = df['new_Date'].dt.month
df['Day'] = df['new_Date'].dt.day
df.set_index('Year',inplace=True) # .set_index() 를 써서 'Year'를 인덱스로 세팅한다.
df.head()
# print(type(df))

Close  Start   High    Low  Volume   new_Date  Month  Day
Year                                                           
2018  10100  10850  10900  10000  137977 2018-07-02      7    2
2018  10700  10550  10900   9990  170253 2018-06-29      6   29
2018  10400  10900  10950  10150  155769 2018-06-28      6   28
2018  10900  10800  11050  10500  133548 2018-06-27      6   27
2018  10800  10900  11000  10700   63039 2018-06-26      6   26

In [ ]:
stock_df = pd.read_csv('C:/workspace/cakd3/pandas/stock-data.csv')
stock_df

In [ ]:
df['stock_df'] = pd.to_datetime(df['stock_df'])
# type(df)

### Q17. titanic 데이터셋에서 5개 열을 선택해서 class열을 기준으로 그룹화를 수행한 후 아래와 같이 출력하였다. 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

In [169]:
# A.
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic') # sns.load_dataset('파일명') 으로 불러오네.
                                      # C:\Users\Ha dowon\seaborn-data 에 있다. seaborn은 seaborn-date 파일을 따로 둔다.
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']] # 5개 열을 선택해서 df(데이터프레임)로 만들었네.

print(df.head())
print()
# class 열을 기준으로 그룹화(1개 열을 기준)
grouped = df.groupby(['class']) # .groupby() 안의 인자를 기준으로 그룹화 수행하는 함수 -> 안에 인자는 ['열 이름']
print('그룹별 평균')
average = grouped.mean() # 그룹별 평균
print(average)
print()
print('그룹별 최대값')
stat = grouped.max() # 그룹별 최대값
print(stat)

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

그룹별 평균
              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

그룹별 최대값
         age   sex      fare  survived
class                                 
First   80.0  male  512.3292         1
Second  70.0  male   73.5000         1
Third   74.0  male   69.5500         1


In [25]:
# 뭐냐 이건.. 어처구니가 없구만.
g_filter = df.filter(['class'])
g_filter

class
0     Third
1     First
2     Third
3     First
4     Third
..      ...
886  Second
887   First
888   Third
889   First
890   Third

[891 rows x 1 columns]

### Q18. titanic 데이터셋에서 'Third'그룹만을 선택해서 group3 이름으로 저장하고 통계요약표를 출력하세요.

In [182]:
# A.
# 개별 그룹 선택하기
group3 = grouped.get_group('Third') # grouped.get_group() 로 그룹 하나를 선택한다. -> grouped.get_group() 는 하나로 연결된 함수다.
# print(group3)
group3.describe() # .describe() 는 통계요약표 출력 함수.

age        fare    survived
count  355.000000  491.000000  491.000000
mean    25.140620   13.675550    0.242363
std     12.495398   11.778142    0.428949
min      0.420000    0.000000    0.000000
25%     18.000000    7.750000    0.000000
50%     24.000000    8.050000    0.000000
75%     32.000000   15.500000    0.000000
max     74.000000   69.550000    1.000000

### Q19. titanic 데이터셋에서 class 열, sex열 기준으로 그룹화한 후 그룹별 평균과 표준편차를 구하세요.

In [ ]:
# A.
grouped = df.groupby(['class', 'sex']) 
gdf = grouped.mean() # mean()  평균
print(gdf)
print()
gdf = grouped.std() # std()  표준편차 standard deviation 의 약자다.
print(gdf)

In [23]:
# 굳이 이렇게 불러오기부터 할 필요가 없다.
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### Q20.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [191]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [192]:
# 1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 
# 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 

# A-1.
df.columns
df1 = df[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck']] # df에서 중복 칼럼 고려하여 삭제한다.
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [194]:
# 2. 풀이에 필요
df1.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [201]:
# 2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 
# df2 이름으로 저장하고 출력하세요.

# A-2.
df2 = df1.drop('deck',axis=1) # 'deck' 은 df1에서 null값이 50% 이상인 칼럼이다. -> 삭제
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [207]:
# 3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 
## 결측값 은 null 이지.
## 대체처리가 뭐지?  -> ,inplace=True
## copy해서 대체 처리한 후 삭제하니까. 대체처리라고 부를 수 있다.
# A-3.
df2.age.isnull().sum()
# 위 구문 결괏값은 177 나온다.

df2.age.fillna(df2.age.mean(),inplace=True) # 여기서 평균값으로 대체 처리를 수행
df2.age.isnull().sum() # 그리고 다시 결측값을 확인해본다.

0

In [208]:
# 4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 
## embarked 칼럼에도 결측값이 2개 있다.

## 앞 행의 값으로 대체 처리를 하라는 게 무슨 말이지? 앞 행은 fare 인데?
## -> 
# A-4.
df2.embarked.isnull().sum()
df2.embarked.fillna(method='ffill',inplace=True) #@ method='ffill' 가 뭐지?
df2.embarked.isnull().sum()

0

In [210]:
# 5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 
# df2.info()를 출력하세요

## sklearn 에서 preprocessing 을 import 한다.

# A5.
from sklearn import preprocessing

features = ['sex','embarked'] # 문자로 되어 있는 칼럼들
for feature in features: # features 변수의 칼럼들에서 하나하나 뽑아낸다. 인코딩 하려고.
    le = preprocessing.LabelEncoder() # preprocessing.LabelEncoder() -> 인코딩 수행
    df2[feature] = le.fit_transform(df2[feature]) # .fit_transform() 으로 숫자로 변환한다.
            # df2의 feature에 해당하는 걸 숫자로 변환. feature은 sex 컬럼과 embarked 칼럼에서 하나하나 뽑아낸 거지.
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    int64  
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB
